server:
  port: 8088

spring:
  application:
    name: config-server
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/yangboonline/config-respo.git
          username: yangboonline
          password: yangbo0512
          search-paths: '{application}'
        native:
          search-locations: /Java/iwork/config
  security:
    user:
      name: admin
      password: admin
  profiles:
    active: native # native指定本地, 生成环境务必在启动命令中指定 -Dspring.profiles.active=prod