server:
  port: 8088

spring:
  application:
    name: config-server
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/yangboonline/config-respo.git
          username: yangboonline
          password: yangbo0512
          search-paths: '{application}'
  security:
    user:
      name: admin
      password: admin