spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/yangboonline/demo/tree/master/config-respo
          username: yangboonline
          password: yangbo0512
          search-paths: '{application}'
      label: master

server:
  port: 8088